CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_name" varchar,
  "password" varchar,
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar,
  "phone_number" varchar,
  "address" varchar,
  "status_id" int,
  "role_id" int,
  "is_delete" bool DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "status" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "code" varchar,
  "name" varchar,
  "type" varchar(8),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "role" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "code" varchar,
  "name" varchar,
  "description" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "external_user" (
  "user_id" integer NOT NULL,
  "sso_user_id" varchar PRIMARY KEY NOT NULL,
  "category_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "category" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "code" varchar,
  "type" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

ALTER TABLE "external_user" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "user" ADD FOREIGN KEY ("status_id") REFERENCES "status" ("id");

ALTER TABLE "user" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id");

ALTER TABLE "external_user" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id");
